/// Flutter icons Eschr
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Eschr
///      fonts:
///       - asset: fonts/Eschr.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Eschr {
  Eschr._();

  static const _kFontFam = 'Eschr';
  static const String _kFontPkg = null;

  static const IconData proj_eschrus__1_ =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
