/// Flutter icons Instagram
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Instagram
///      fonts:
///       - asset: fonts/Instagram.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Instagram {
  Instagram._();

  static const _kFontFam = 'Instagram';
  static const String _kFontPkg = null;

  static const IconData icons8_instagram =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
