/// Flutter icons MouthFeel
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MouthFeel
///      fonts:
///       - asset: fonts/MouthFeel.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MouthFeel {
  MouthFeel._();

  static const _kFontFam = 'MouthFeel';
  static const String _kFontPkg = null;

  static const IconData noun_smiling_mouth_1172516 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
