/// Flutter icons Spiciness
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Spiciness
///      fonts:
///       - asset: fonts/Spiciness.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Spiciness {
  Spiciness._();

  static const _kFontFam = 'Spiciness';
  static const String _kFontPkg = null;

  static const IconData noun_spicy_3017538 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
